
CREATE TABLE `QSO_RATES` (
	`CONTEST` VARCHAR(50) NOT NULL,
	`YEAR` INT(4) NOT NULL,
	`CALL` VARCHAR(200) NOT NULL,
	`OPERATORS` VARCHAR(500) NULL DEFAULT NULL,
	`QHOUR` INT(4) NULL DEFAULT NULL,
	`QHOUR_START` VARCHAR(20) NULL DEFAULT NULL,
	`QRATE` INT(4) NULL DEFAULT NULL,
	`QRATE_START` VARCHAR(20) NULL DEFAULT NULL,
	`OPERATOR` VARCHAR(50) NULL DEFAULT NULL,
	`TRANSMITTER` VARCHAR(50) NULL DEFAULT NULL,
	`ASSISTED` VARCHAR(50) NULL DEFAULT NULL,
	`BAND` VARCHAR(50) NULL DEFAULT NULL,
	`POWER` VARCHAR(50) NULL DEFAULT NULL,
	`COUNTRY_NAME` VARCHAR(100) NULL DEFAULT NULL,
	`COUNTRY_PFX` VARCHAR(8) NULL DEFAULT NULL,
	`CONTINENT` VARCHAR(2) NULL DEFAULT NULL,
	`WAZ` INT(2) NULL DEFAULT NULL,
	`ITU` INT(2) NULL DEFAULT NULL,
	PRIMARY KEY (`CONTEST`, `YEAR`, `CALL`),
	INDEX `CONTEST_YEAR_CALL_COUNTRY_PFX_CONTINENT_WAZ` (`CONTEST`, `YEAR`, `CALL`, `COUNTRY_PFX`, `CONTINENT`, `WAZ`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
