
CREATE TABLE `site` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`URL` VARCHAR(500) NOT NULL,
	`Host` VARCHAR(500) NULL,
	`Robots` TINYINT(1) NULL,
	`RobotHost` VARCHAR(500) NULL,
	`Done` TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT