//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PriceProcessor.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseContext object using the connection string found in the 'DatabaseContext' section of the application configuration file.
        /// </summary>
        public DatabaseContext() : base("name=DatabaseContext", "DatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseContext object.
        /// </summary>
        public DatabaseContext(string connectionString) : base(connectionString, "DatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseContext object.
        /// </summary>
        public DatabaseContext(EntityConnection connection) : base(connection, "DatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WebTask> WebTasks
        {
            get
            {
                if ((_WebTasks == null))
                {
                    _WebTasks = base.CreateObjectSet<WebTask>("WebTasks");
                }
                return _WebTasks;
            }
        }
        private ObjectSet<WebTask> _WebTasks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Engine> Engines
        {
            get
            {
                if ((_Engines == null))
                {
                    _Engines = base.CreateObjectSet<Engine>("Engines");
                }
                return _Engines;
            }
        }
        private ObjectSet<Engine> _Engines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ViewNewSearch> ViewNewSearches
        {
            get
            {
                if ((_ViewNewSearches == null))
                {
                    _ViewNewSearches = base.CreateObjectSet<ViewNewSearch>("ViewNewSearches");
                }
                return _ViewNewSearches;
            }
        }
        private ObjectSet<ViewNewSearch> _ViewNewSearches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApprovalItem> ApprovalItems
        {
            get
            {
                if ((_ApprovalItems == null))
                {
                    _ApprovalItems = base.CreateObjectSet<ApprovalItem>("ApprovalItems");
                }
                return _ApprovalItems;
            }
        }
        private ObjectSet<ApprovalItem> _ApprovalItems;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ViewApprovalList> ViewApprovalLists
        {
            get
            {
                if ((_ViewApprovalLists == null))
                {
                    _ViewApprovalLists = base.CreateObjectSet<ViewApprovalList>("ViewApprovalLists");
                }
                return _ViewApprovalLists;
            }
        }
        private ObjectSet<ViewApprovalList> _ViewApprovalLists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ViewUpdate> ViewUpdates
        {
            get
            {
                if ((_ViewUpdates == null))
                {
                    _ViewUpdates = base.CreateObjectSet<ViewUpdate>("ViewUpdates");
                }
                return _ViewUpdates;
            }
        }
        private ObjectSet<ViewUpdate> _ViewUpdates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductPriceInfo> ProductPriceInfoes
        {
            get
            {
                if ((_ProductPriceInfoes == null))
                {
                    _ProductPriceInfoes = base.CreateObjectSet<ProductPriceInfo>("ProductPriceInfoes");
                }
                return _ProductPriceInfoes;
            }
        }
        private ObjectSet<ProductPriceInfo> _ProductPriceInfoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebTasks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebTasks(WebTask webTask)
        {
            base.AddObject("WebTasks", webTask);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Engines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEngines(Engine engine)
        {
            base.AddObject("Engines", engine);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ViewNewSearches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViewNewSearches(ViewNewSearch viewNewSearch)
        {
            base.AddObject("ViewNewSearches", viewNewSearch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApprovalItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApprovalItems(ApprovalItem approvalItem)
        {
            base.AddObject("ApprovalItems", approvalItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ViewApprovalLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViewApprovalLists(ViewApprovalList viewApprovalList)
        {
            base.AddObject("ViewApprovalLists", viewApprovalList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ViewUpdates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViewUpdates(ViewUpdate viewUpdate)
        {
            base.AddObject("ViewUpdates", viewUpdate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductPriceInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductPriceInfoes(ProductPriceInfo productPriceInfo)
        {
            base.AddObject("ProductPriceInfoes", productPriceInfo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ApprovalItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApprovalItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApprovalItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="engineId">Initial value of the EngineId property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static ApprovalItem CreateApprovalItem(global::System.Int64 id, global::System.Int64 engineId, global::System.Int64 productId, global::System.String url, global::System.String name, global::System.Byte status)
        {
            ApprovalItem approvalItem = new ApprovalItem();
            approvalItem.Id = id;
            approvalItem.EngineId = engineId;
            approvalItem.ProductId = productId;
            approvalItem.Url = url;
            approvalItem.Name = name;
            approvalItem.Status = status;
            return approvalItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EngineId
        {
            get
            {
                return _EngineId;
            }
            set
            {
                OnEngineIdChanging(value);
                ReportPropertyChanging("EngineId");
                _EngineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EngineId");
                OnEngineIdChanged();
            }
        }
        private global::System.Int64 _EngineId;
        partial void OnEngineIdChanging(global::System.Int64 value);
        partial void OnEngineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Int64 _ProductId;
        partial void OnProductIdChanging(global::System.Int64 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.String _Price;
        partial void OnPriceChanging(global::System.String value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Byte _Status;
        partial void OnStatusChanging(global::System.Byte value);
        partial void OnStatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Engine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Engine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Engine object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Engine CreateEngine(global::System.Int64 id, global::System.String name)
        {
            Engine engine = new Engine();
            engine.Id = id;
            engine.Name = name;
            return engine;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="productCode">Initial value of the ProductCode property.</param>
        public static Product CreateProduct(global::System.Int64 id, global::System.String name, global::System.String productCode)
        {
            Product product = new Product();
            product.ID = id;
            product.Name = name;
            product.ProductCode = productCode;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                OnProductCodeChanging(value);
                ReportPropertyChanging("ProductCode");
                _ProductCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductCode");
                OnProductCodeChanged();
            }
        }
        private global::System.String _ProductCode;
        partial void OnProductCodeChanging(global::System.String value);
        partial void OnProductCodeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ProductPriceInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductPriceInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductPriceInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="engineId">Initial value of the EngineId property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="inStock">Initial value of the InStock property.</param>
        /// <param name="dateOfCheck">Initial value of the DateOfCheck property.</param>
        public static ProductPriceInfo CreateProductPriceInfo(global::System.Int64 id, global::System.Int64 productId, global::System.Int64 engineId, global::System.Double price, global::System.Boolean inStock, global::System.DateTime dateOfCheck)
        {
            ProductPriceInfo productPriceInfo = new ProductPriceInfo();
            productPriceInfo.Id = id;
            productPriceInfo.ProductId = productId;
            productPriceInfo.EngineId = engineId;
            productPriceInfo.Price = price;
            productPriceInfo.InStock = inStock;
            productPriceInfo.DateOfCheck = dateOfCheck;
            return productPriceInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Int64 _ProductId;
        partial void OnProductIdChanging(global::System.Int64 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EngineId
        {
            get
            {
                return _EngineId;
            }
            set
            {
                OnEngineIdChanging(value);
                ReportPropertyChanging("EngineId");
                _EngineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EngineId");
                OnEngineIdChanged();
            }
        }
        private global::System.Int64 _EngineId;
        partial void OnEngineIdChanging(global::System.Int64 value);
        partial void OnEngineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Double _Price;
        partial void OnPriceChanging(global::System.Double value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean InStock
        {
            get
            {
                return _InStock;
            }
            set
            {
                OnInStockChanging(value);
                ReportPropertyChanging("InStock");
                _InStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InStock");
                OnInStockChanged();
            }
        }
        private global::System.Boolean _InStock;
        partial void OnInStockChanging(global::System.Boolean value);
        partial void OnInStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfCheck
        {
            get
            {
                return _DateOfCheck;
            }
            set
            {
                OnDateOfCheckChanging(value);
                ReportPropertyChanging("DateOfCheck");
                _DateOfCheck = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfCheck");
                OnDateOfCheckChanged();
            }
        }
        private global::System.DateTime _DateOfCheck;
        partial void OnDateOfCheckChanging(global::System.DateTime value);
        partial void OnDateOfCheckChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ViewApprovalList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewApprovalList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ViewApprovalList object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="engineId">Initial value of the EngineId property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="searchName">Initial value of the SearchName property.</param>
        /// <param name="engineName">Initial value of the EngineName property.</param>
        public static ViewApprovalList CreateViewApprovalList(global::System.Int64 id, global::System.Int64 engineId, global::System.Int64 productId, global::System.String url, global::System.String name, global::System.Byte status, global::System.String searchName, global::System.String engineName)
        {
            ViewApprovalList viewApprovalList = new ViewApprovalList();
            viewApprovalList.Id = id;
            viewApprovalList.EngineId = engineId;
            viewApprovalList.ProductId = productId;
            viewApprovalList.Url = url;
            viewApprovalList.Name = name;
            viewApprovalList.Status = status;
            viewApprovalList.SearchName = searchName;
            viewApprovalList.EngineName = engineName;
            return viewApprovalList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EngineId
        {
            get
            {
                return _EngineId;
            }
            set
            {
                if (_EngineId != value)
                {
                    OnEngineIdChanging(value);
                    ReportPropertyChanging("EngineId");
                    _EngineId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EngineId");
                    OnEngineIdChanged();
                }
            }
        }
        private global::System.Int64 _EngineId;
        partial void OnEngineIdChanging(global::System.Int64 value);
        partial void OnEngineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Int64 _ProductId;
        partial void OnProductIdChanging(global::System.Int64 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                if (_Url != value)
                {
                    OnUrlChanging(value);
                    ReportPropertyChanging("Url");
                    _Url = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Url");
                    OnUrlChanged();
                }
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.String _Price;
        partial void OnPriceChanging(global::System.String value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Status
        {
            get
            {
                return _Status;
            }
            set
            {
                if (_Status != value)
                {
                    OnStatusChanging(value);
                    ReportPropertyChanging("Status");
                    _Status = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Status");
                    OnStatusChanged();
                }
            }
        }
        private global::System.Byte _Status;
        partial void OnStatusChanging(global::System.Byte value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SearchName
        {
            get
            {
                return _SearchName;
            }
            set
            {
                if (_SearchName != value)
                {
                    OnSearchNameChanging(value);
                    ReportPropertyChanging("SearchName");
                    _SearchName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SearchName");
                    OnSearchNameChanged();
                }
            }
        }
        private global::System.String _SearchName;
        partial void OnSearchNameChanging(global::System.String value);
        partial void OnSearchNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EngineName
        {
            get
            {
                return _EngineName;
            }
            set
            {
                if (_EngineName != value)
                {
                    OnEngineNameChanging(value);
                    ReportPropertyChanging("EngineName");
                    _EngineName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EngineName");
                    OnEngineNameChanged();
                }
            }
        }
        private global::System.String _EngineName;
        partial void OnEngineNameChanging(global::System.String value);
        partial void OnEngineNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ViewNewSearch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewNewSearch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ViewNewSearch object.
        /// </summary>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="engineId">Initial value of the EngineId property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        public static ViewNewSearch CreateViewNewSearch(global::System.Int64 productId, global::System.Int64 engineId, global::System.String productName)
        {
            ViewNewSearch viewNewSearch = new ViewNewSearch();
            viewNewSearch.ProductId = productId;
            viewNewSearch.EngineId = engineId;
            viewNewSearch.ProductName = productName;
            return viewNewSearch;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Int64 _ProductId;
        partial void OnProductIdChanging(global::System.Int64 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EngineId
        {
            get
            {
                return _EngineId;
            }
            set
            {
                if (_EngineId != value)
                {
                    OnEngineIdChanging(value);
                    ReportPropertyChanging("EngineId");
                    _EngineId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EngineId");
                    OnEngineIdChanged();
                }
            }
        }
        private global::System.Int64 _EngineId;
        partial void OnEngineIdChanging(global::System.Int64 value);
        partial void OnEngineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                if (_ProductName != value)
                {
                    OnProductNameChanging(value);
                    ReportPropertyChanging("ProductName");
                    _ProductName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ProductName");
                    OnProductNameChanged();
                }
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ViewUpdate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewUpdate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ViewUpdate object.
        /// </summary>
        /// <param name="engineId">Initial value of the EngineId property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static ViewUpdate CreateViewUpdate(global::System.Int64 engineId, global::System.Int64 productId, global::System.String url)
        {
            ViewUpdate viewUpdate = new ViewUpdate();
            viewUpdate.EngineId = engineId;
            viewUpdate.ProductId = productId;
            viewUpdate.Url = url;
            return viewUpdate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EngineId
        {
            get
            {
                return _EngineId;
            }
            set
            {
                if (_EngineId != value)
                {
                    OnEngineIdChanging(value);
                    ReportPropertyChanging("EngineId");
                    _EngineId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EngineId");
                    OnEngineIdChanged();
                }
            }
        }
        private global::System.Int64 _EngineId;
        partial void OnEngineIdChanging(global::System.Int64 value);
        partial void OnEngineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Int64 _ProductId;
        partial void OnProductIdChanging(global::System.Int64 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                if (_Url != value)
                {
                    OnUrlChanging(value);
                    ReportPropertyChanging("Url");
                    _Url = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Url");
                    OnUrlChanged();
                }
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="WebTask")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WebTask : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WebTask object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="errors">Initial value of the Errors property.</param>
        /// <param name="taskType">Initial value of the TaskType property.</param>
        /// <param name="engineId">Initial value of the EngineId property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        public static WebTask CreateWebTask(global::System.Int64 id, global::System.String url, global::System.Byte status, global::System.Byte errors, global::System.Byte taskType, global::System.Int64 engineId, global::System.Int64 productId)
        {
            WebTask webTask = new WebTask();
            webTask.Id = id;
            webTask.Url = url;
            webTask.Status = status;
            webTask.Errors = errors;
            webTask.TaskType = taskType;
            webTask.EngineId = engineId;
            webTask.ProductId = productId;
            return webTask;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Byte _Status;
        partial void OnStatusChanging(global::System.Byte value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Errors
        {
            get
            {
                return _Errors;
            }
            set
            {
                OnErrorsChanging(value);
                ReportPropertyChanging("Errors");
                _Errors = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Errors");
                OnErrorsChanged();
            }
        }
        private global::System.Byte _Errors;
        partial void OnErrorsChanging(global::System.Byte value);
        partial void OnErrorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte TaskType
        {
            get
            {
                return _TaskType;
            }
            set
            {
                OnTaskTypeChanging(value);
                ReportPropertyChanging("TaskType");
                _TaskType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaskType");
                OnTaskTypeChanged();
            }
        }
        private global::System.Byte _TaskType;
        partial void OnTaskTypeChanging(global::System.Byte value);
        partial void OnTaskTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EngineId
        {
            get
            {
                return _EngineId;
            }
            set
            {
                OnEngineIdChanging(value);
                ReportPropertyChanging("EngineId");
                _EngineId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EngineId");
                OnEngineIdChanged();
            }
        }
        private global::System.Int64 _EngineId;
        partial void OnEngineIdChanging(global::System.Int64 value);
        partial void OnEngineIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Int64 _ProductId;
        partial void OnProductIdChanging(global::System.Int64 value);
        partial void OnProductIdChanged();

        #endregion
    
    }

    #endregion
    
}
